name: CoreDNS

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Init
      run: go mod tidy

    - name: Build CoreDNS
      run: |
        git clone https://github.com/coredns/coredns
        pushd coredns
        mkdir -p plugin/dnsimple
        cp ../*.go plugin/dnsimple
        cp ../go.mod plugin/dnsimple
        sed -i "/^go ${{env.GO_VERSION}}/a replace github.com/dnsimple/coredns-dnsimple => ./plugin/dnsimple" go.mod
        sed -i '/route53:route53/i dnsimple:github.com\/dnsimple\/coredns-dnsimple' plugin.cfg
        GOFLAGS=-mod=mod go generate
        go mod tidy
        go build
