name: Docker

on:
  push:
    tags:
      - v*.*.*

env:
  GO_VERSION: '1.20'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: 'refs/heads/main'
          check-name: 'Run tests'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Prepare CoreDNS with DNSimple Plugin
        run: |
          git clone https://github.com/coredns/coredns
          pushd coredns
          mkdir -p plugin/dnsimple
          cp ../*.go plugin/dnsimple
          cp ../go.mod plugin/dnsimple
          sed -i "/^go ${{env.GO_VERSION}}/a replace github.com/dnsimple/coredns-dnsimple => ./plugin/dnsimple" go.mod
          sed -i '/route53:route53/i dnsimple:github.com\/dnsimple\/coredns-dnsimple' plugin.cfg
          GOFLAGS=-mod=mod go generate
          go mod tidy
          cp ../Dockerfile.release .
          rm .dockerignore

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./coredns
          file: ./coredns/Dockerfile.release
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            dnsimple/coredns:latest
            dnsimple/coredns:${{ github.ref_name }}
