---
name: Docker

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

env:
  REGISTRY_IMAGE: dnsimple/coredns

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.5.0
        with:
          ref: 'refs/heads/main'
          check-name: 'Run tests'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success

      - name: Checkout
        uses: actions/checkout@v6

      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@v2
        id: versions

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Prepare CoreDNS with DNSimple Plugin
        run: |
          git clone https://github.com/coredns/coredns
          pushd coredns
          mkdir -p plugin/dnsimple
          cp ../*.go plugin/dnsimple
          cp ../go.mod plugin/dnsimple
          sed -i "/^go /a replace github.com/dnsimple/coredns-dnsimple => ./plugin/dnsimple" go.mod
          sed -i '/route53:route53/i dnsimple:github.com\/dnsimple\/coredns-dnsimple' plugin.cfg
          GOFLAGS=-mod=mod go generate
          go mod tidy
          cp ../Dockerfile.release .
          cp ../bin/_docker/docker-entrypoint.sh .
          rm .dockerignore

      - name: Set up Depot CLI
        uses: depot/setup-action@v1.7.1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.10.0
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=semver,pattern=v{{version}},enable=${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Login to Docker Hub
        uses: docker/login-action@v4.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: build
        uses: depot/build-push-action@v1.17.0
        with:
          project: dxthxsc4l9
          token: ${{ secrets.DEPOT_PROJECT_TOKEN }}
          context: ./coredns
          file: ./coredns/Dockerfile.release
          build-args: |
            GOLANG_VERSION=${{ steps.versions.outputs.golang }}
          platforms: ${{ matrix.platform }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v6
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Download digests
        uses: actions/download-artifact@v7
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.12.0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.10.0
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=semver,pattern=v{{version}},enable=${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Login to Docker Hub
        uses: docker/login-action@v4.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}
