name: Release

on:
  push:
    tags:
      - v*.*.*

env:
  GO_VERSION: '1.20'

jobs:
  publish:
    name: Release CoreDNS with DNSimple Plugin
    runs-on: ubuntu-22.04

    steps:
      # - name: Wait for tests to succeed
      #   uses: lewagon/wait-on-check-action@v1.3.1
      #   with:
      #     ref: 'refs/heads/main'
      #     running-workflow-name: 'Release CoreDNS with DNSimple Plugin'
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     wait-interval: 10
      #     allowed-conclusions: success

      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Build CoreDNS with DNSimple Plugin
        run: |
          pluginDir="$PWD"
          git clone https://github.com/coredns/coredns
          pushd coredns
          echo "sed -i \"s%^go ${{env.GO_VERSION}}%go ${{env.GO_VERSION}}\nreplace github.com/dnsimple/coredns-dnsimple => $pluginDir%\" go.mod"
          sed -i "s%^go ${{env.GO_VERSION}}%go ${{env.GO_VERSION}}\nreplace github.com/dnsimple/coredns-dnsimple => $pluginDir%" go.mod
          sed -i 's%route53:route53%dnsimple:github.com/dnsimple/coredns-dnsimple%' plugin.cfg
          GOFLAGS=-mod=mod go generate
          go mod tidy
          cp ../Makefile.release .
          make release -f Makefile.release
          popd

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*.tar.gz
