---
name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    name: Release CoreDNS with DNSimple Plugin
    runs-on: ubuntu-latest

    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.4.0
        with:
          ref: 'refs/heads/main'
          check-name: 'Run tests'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Build CoreDNS with DNSimple Plugin
        run: |
          git clone https://github.com/coredns/coredns
          pushd coredns
          pluginDir="$PWD/plugin/dnsimple"
          mkdir -p plugin/dnsimple
          cp ../*.go plugin/dnsimple
          cp ../go.mod plugin/dnsimple
          sed -i "/^go ${{ steps.versions.outputs.golang }}/a replace github.com/dnsimple/coredns-dnsimple => $pluginDir" go.mod
          sed -i '/route53:route53/i dnsimple:github.com\/dnsimple\/coredns-dnsimple' plugin.cfg
          GOFLAGS=-mod=mod go generate
          go mod tidy
          cp ../Makefile.release .
          make release -f Makefile.release
          popd

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: coredns/release/*.tar.gz
